name: Android CI
on:
  pull_request_target:
    branches:
      - master
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: upload artifact to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ env.SERVICE_ACCOUNT_JSON }}
          packageName: com.shashank.memebase
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: beta
          status: inProgress
          inAppUpdatePriority: 2
          userFraction: 1.00
          whatsNewDirectory: distribution/whatsNewDirectory
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          debugSymbols: app/intermediates/merged_native_libs/release/out/lib